use_frameworks!

target 'RxCoreBluetooth_Example' do
  pod 'RxCoreBluetooth', :path => '../'
  
  pod 'RxSwift'
  pod 'RxCocoa'
  
  target 'RxCoreBluetooth_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
    pod 'Nimble', '~> 5.1.1'
  end
end
